[package]
name = "ne_input"
version = "0.1.0"
edition = "2021"
homepage = "https://nightmare-corp.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
path = "src/ne_input.rs" 