[package]
name = "scene_example_game"
version = "0.1.0"
edition = "2021"
homepage = "https://nightmare-corp.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nightmare_engine = {path = "../"}
