[package]
name = "ne_task"
version = "0.1.0"
edition = "2021"
description = "State of the art task scheduler"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
path = "src/ne_task.rs" 