[package]
name = "ne_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ne_ecs = {path = "../ne_ecs"}
ne = { path = "../ne" }
num_cpus = "1.13.1"

tracing = "0.1.35"