[package]
name = "ne_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = { version = "0.12", features = ["serde"] }
ahash = "0.7.0"


[lib]
path = "src/ne_utils.rs" 
